---
# Terraria Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  labels:
    app: terraria
    name: terraria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
      task: terraria
  template:
    metadata:
      labels:
        app: terraria
        task: terraria
    spec:
      containers:
        - name: terraria
          image: beardedio/terraria
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
          ports:
            - containerPort: 7777
          env:
            - name: world
              value: 'maximiliannetwork.wld'
          volumeMounts:
            - name: terraria-pvc
              mountPath: /config
      volumes:
        - name: terraria-pvc
          persistentVolumeClaim:
            claimName: terraria-pvc
