version: "3.9"
services:
  ksplmp:
    container_name: ksplmp
    image: dockrbyter/ksplmp:latest
    volumes:
      - $HOME/ksplmp:/ksp/Config
      - $HOME/ksplmp/universe:/ksp/Universe
      - $HOME/ksplmp/LMPModControl.xml:/ksplmp/LMPModControl.xml
    environment:
      PORTGAME: 8800
    ports:
      - "8800:8800/udp"

#   Docker-Compose File: Kerbal Space Program LMP
#   https://github.com/dockrbyter/GameServer/tree/master/Docker/Linux/KSP-LMP
