version: "3.9"
services:
  vrising:
    image: trueosiris/vrising
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - SERVERNAME=YOURvrisingSERVER
    volumes:
      - $HOME/vrising/srv:/mnt/vrising/server:rw
      - $HOME/vrising/data:/mnt/vrising/persistentdata:rw
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'

#   Docker-Compose File: V Rising
#   https://github.com/dockrbyter/GameServer/tree/master/Docker/Linux/
